"""
Django settings for collectAndSendEmailAdmin project.

Generated by 'django-admin startproject' using Django 4.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
WORD_TEMPLATE_PATH = 'docx/template_1.docx'

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-5!h1+)+-xkkwj0nyra=3^ea70fsf68#1!^l!1y&hji)@!zbbmi"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']
CORS_ALLOWED_ORIGINS = ['http://127.0.0.1:8000']
CORS_ALLOW_ALL_ORIGINS = True
# Application definition

INSTALLED_APPS = [
    'simpleui',
    "django.contrib.admin", "django.contrib.auth",
    "django.contrib.contenttypes", "django.contrib.sessions",
    "django.contrib.messages", "django.contrib.staticfiles",
    "collectAndSendEmailAdmin"
]

SIMPLEUI_ANALYSIS = False
# 后台管理页面：兰大 logo 与标题
SIMPLEUI_LOGO = '/media/logo.jpg'  # 侧边栏 logo，需确保 media/logo.jpg 存在
# 主题与界面优化
SIMPLEUI_DEFAULT_THEME = 'admin.lte.css'  # Admin LTE 风格，简洁专业
SIMPLEUI_HOME_INFO = False   # 隐藏首页服务器信息
SIMPLEUI_HOME_QUICK = False  # 隐藏快速操作
SIMPLEUI_HOME_ACTION = False # 隐藏最近动作
SIMPLEUI_LOADING = False     # 关闭 Loading 遮罩

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    'corsheaders.middleware.CorsMiddleware',
    "django.middleware.common.CommonMiddleware",
    # "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

CSRF_TRUSTED_ORIGINS = [
    'https://*.riker.replit.dev',
    'https://*.replit.app',

    # If there are any other domains you serve your application through, add them here.
]

ROOT_URLCONF = "collectAndSendEmailAdmin.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, 'collectAndSendEmail/templates'), os.path.join(BASE_DIR, 'templates')],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "collectAndSendEmailAdmin.wsgi.application"

# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
        # 'NAME': 'graduate',
        # 'USER': 'test_root',
        # 'PASSWORD': 'YSYS3746root',
        # 'HOST': '127.0.0.1',
        # 'PORT': 3306
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME":
        "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME":
        "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME":
        "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME":
        "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format':
            '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'django.log'),
            'encoding': 'utf-8',  # 指定文件编码为utf-8
            'formatter': 'verbose',
        },
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file', 'console'],
            'level': 'INFO',  # 可以根据需要设置为INFO, WARNING, ERROR等
            'propagate': True,
        },
    },
}

# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'zh-hans'
TIME_ZONE = 'Asia/Shanghai'
USE_I18N = True
USE_L10N = True
# 不适用 UTC 时间，使用本地时间
# USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = "/static/"
STATICFILES_DIRS = [str(BASE_DIR / "static")] if (BASE_DIR / "static").exists() else []
MEDIA_URL = 'media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# 邮件 SMTP 配置：本地测试(DEBUG=True)用 QQ 邮箱，部署(DEBUG=False)用兰大邮箱；环境变量可覆盖
if DEBUG:
    # 本地测试 - QQ 邮箱（465 端口 SSL 更稳定，587 易出现 Connection closed）
    EMAIL_SMTP_SERVER = os.environ.get("EMAIL_SMTP_SERVER", "smtp.qq.com")
    EMAIL_SMTP_PORT = int(os.environ.get("EMAIL_SMTP_PORT", "465"))
    EMAIL_SMTP_USER = os.environ.get("EMAIL_SMTP_USER", "1326906378@qq.com")
    EMAIL_SMTP_PASSWORD = os.environ.get("EMAIL_SMTP_PASSWORD", "dzsmoyphmiypjiab")
    EMAIL_SENDER = os.environ.get("EMAIL_SENDER", "1326906378@qq.com")
    EMAIL_RECEIVER = os.environ.get("EMAIL_RECEIVER", "1326906378@qq.com")
    EMAIL_CC = os.environ.get("EMAIL_CC", "1326906378@qq.com")
    EMAIL_USE_SSL = os.environ.get("EMAIL_USE_SSL", "true").lower() in ("1", "true", "yes")  # 465 需 SSL
    EMAIL_USE_STARTTLS = os.environ.get("EMAIL_USE_STARTTLS", "false").lower() in ("1", "true", "yes")  # 465 不用 starttls
else:
    # 部署到服务器 - 兰大邮箱
    EMAIL_SMTP_SERVER = os.environ.get("EMAIL_SMTP_SERVER", "smtp.lzu.edu.cn")
    EMAIL_SMTP_PORT = int(os.environ.get("EMAIL_SMTP_PORT", "25"))
    EMAIL_SMTP_USER = os.environ.get("EMAIL_SMTP_USER", "xscglk@lzu.edu.cn")
    EMAIL_SMTP_PASSWORD = os.environ.get("EMAIL_SMTP_PASSWORD", "aeAqjvJfprXFADz2")
    EMAIL_SENDER = os.environ.get("EMAIL_SENDER", "xscglk@lzu.edu.cn")
    EMAIL_RECEIVER = os.environ.get("EMAIL_RECEIVER", "dangag@lzu.edu.cn")
    EMAIL_CC = os.environ.get("EMAIL_CC", "xscglk@lzu.edu.cn")
    EMAIL_USE_SSL = os.environ.get("EMAIL_USE_SSL", "false").lower() in ("1", "true", "yes")
    EMAIL_USE_STARTTLS = os.environ.get("EMAIL_USE_STARTTLS", "true").lower() in ("1", "true", "yes")
