# Generated by Django 4.1 on 2024-01-03 04:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collectAndSendEmailAdmin", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Graduate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "g_cert_pic",
                    models.ImageField(upload_to="certificates/", verbose_name="毕业证书照片"),
                ),
                ("g_name", models.CharField(max_length=256, verbose_name="姓名")),
                (
                    "g_sex",
                    models.SmallIntegerField(
                        choices=[(0, "男"), (1, "女")], verbose_name="性别"
                    ),
                ),
                ("g_college", models.CharField(max_length=256, verbose_name="毕业学院")),
                ("g_major", models.CharField(max_length=256, verbose_name="专业名称")),
                (
                    "g_cert_date",
                    models.DateField(
                        validators=[
                            django.core.validators.MinValueValidator(
                                1000, message="年份必须为4位数字"
                            ),
                            django.core.validators.MaxValueValidator(
                                9999, message="年份必须为4位数字"
                            ),
                        ],
                        verbose_name="毕业年份",
                    ),
                ),
                ("g_id_no", models.IntegerField(verbose_name="身份证号")),
                ("g_phone", models.IntegerField(verbose_name="联系方式")),
                (
                    "g_mailing_address",
                    models.TextField(max_length=1024, verbose_name="邮寄地址"),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Position",
        ),
    ]
