# Generated by Django 4.1 on 2024-01-03 05:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collectAndSendEmailAdmin", "0002_graduate_delete_position"),
    ]

    operations = [
        migrations.AlterField(
            model_name="graduate",
            name="g_cert_date",
            field=models.IntegerField(
                default=2024,
                validators=[
                    django.core.validators.MinValueValidator(1000, message="年份必须为4位数字"),
                    django.core.validators.MaxValueValidator(9999, message="年份必须为4位数字"),
                ],
                verbose_name="毕业年份",
            ),
        ),
        migrations.AlterField(
            model_name="graduate",
            name="g_sex",
            field=models.SmallIntegerField(
                choices=[(0, "男"), (1, "女")], default=0, verbose_name="性别"
            ),
        ),
    ]
