# Generated by Django 4.1 on 2024-01-03 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "collectAndSendEmailAdmin",
            "0004_alter_graduate_g_cert_date_alter_graduate_g_id_no_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="graduate",
            options={"verbose_name": "毕业生", "verbose_name_plural": "毕业生"},
        ),
        migrations.AddField(
            model_name="graduate",
            name="audit_status",
            field=models.IntegerField(
                choices=[(0, "未审核"), (1, "审核通过"), (2, "审核不通过")],
                default=0,
                verbose_name="审核状态",
            ),
        ),
        migrations.AddField(
            model_name="graduate",
            name="email_sent_time",
            field=models.DateTimeField(blank=True, null=True, verbose_name="邮件发送时间"),
        ),
        migrations.AddField(
            model_name="graduate",
            name="email_status",
            field=models.IntegerField(
                choices=[(0, "未发送"), (1, "发送成功"), (2, "发送失败")],
                default=0,
                verbose_name="邮件发送状态",
            ),
        ),
    ]
