# Generated by Django 4.1 on 2024-01-03 16:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "collectAndSendEmailAdmin",
            "0005_alter_graduate_options_graduate_audit_status_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="graduate",
            old_name="g_cert_date",
            new_name="g_year",
        ),
        migrations.AlterField(
            model_name="graduate",
            name="g_id_no",
            field=models.CharField(
                max_length=18,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "\\d{17}[\\dX]", message="无效的身份证号"
                    )
                ],
                verbose_name="身份证号",
            ),
        ),
    ]
