# Generated by Django 4.1 on 2024-01-04 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "collectAndSendEmailAdmin",
            "0006_rename_g_cert_date_graduate_g_year_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="graduate",
            name="audit_status",
            field=models.IntegerField(
                choices=[(0, "未审核"), (1, "通过"), (2, "不通过")],
                default=0,
                verbose_name="审核状态",
            ),
        ),
        migrations.AlterField(
            model_name="graduate",
            name="email_status",
            field=models.IntegerField(
                choices=[(0, "未发送"), (1, "成功"), (2, "失败")],
                default=0,
                verbose_name="邮件发送状态",
            ),
        ),
    ]
