# Generated by Django 4.1 on 2024-02-02 14:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("collectAndSendEmailAdmin", "0007_alter_graduate_audit_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="graduate",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
