# Generated by Django 4.1 on 2024-02-02 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collectAndSendEmailAdmin", "0008_graduate_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="graduate",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
        ),
    ]
