# Generated by Django 4.1 on 2024-02-02 15:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("collectAndSendEmailAdmin", "0009_alter_graduate_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="graduate",
            name="g_email",
            field=models.TextField(
                default=django.utils.timezone.now, max_length=1024, verbose_name="邮箱"
            ),
            preserve_default=False,
        ),
    ]
